### ISSUE TITLE
lib/check doesn't support passing shrinkwrap as object

### ISSUE THREAD

**Issue by mmgm** [nodesecurity/nsp#103]
I can see that there is some code there that tries to identify whether or not the passed shrinkwrap is a string (and therefore probably a file path) and requires it if so.

However, later on in the file, the shrinkwrap path is read from the filesystem, even if we earlier deduced that it wasn't a file path but a ready to use object.

It seems like a bug, and I'd be happy to quickly fix it myself and submit a pull request. I just wanted to make sure that this is indeed a bug and not a design choice that I was not aware of, and that my pull request is likely to find itself merged here.

Thanks.

**Comment by evilpacket** [comment]
That's a good question. I'm not sure. It's possible it's part of the code climate integration. @nlf will probably know. Be patient with a slow response as we're heads down trying to push out a few features. Once he clarifies we'll know for sure :)

**Comment by nlf** [comment]
this issue is specific to the offline mode, which was written to support codeclimate. normal online usage works correctly.

that said we should still change it. if you've got the time and want to submit a PR i'd be happy to merge it, otherwise i'll get to it myself in the next few days

**Comment by mmgm** [comment]
Thanks for getting back to me. I'm personally interested in seeing this issue fixed ASAP, so you can expect to see a pull request later today and hopefully you'll be happy to merge it.

**Comment by evilpacket** [comment]
Curious, What's your use case that it needs to be an object?

**Comment by mmgm** [comment]
Hey,
Sorry if I'm being a pain, but it's been a few days since I posted my pull request, and as I said, I'd love to see this fix merged. Is there anything about my fix that's holding you back from merging it? Anything else I can do to help this process along?

**Comment by nlf** [comment]
published as 2.3.3. sorry for the delay, we're working on hard on a bunch of new features :)
