### ISSUE TITLE
Advisory 99 should allow v1.6.9 of engine.io-client

### ISSUE THREAD

**Issue by doug-wade** [nodesecurity/nsp#105]
[Release 1.6.9](https://github.com/socketio/engine.io-client/commit/2a7a011932094d4970dc68abd32e78265495a621) contained the fix described in [Advisory 99](https://nodesecurity.io/advisories/99). I find the same with a freshly installed copy

```
dougwade /tmp » grep "rejectUnauthorized ===" node_modules/engine.io-client/engine.io.js
  this.rejectUnauthorized = opts.rejectUnauthorized === undefined ? true : opts.rejectUnauthorized;
dougwade /tmp » npm i engine.io-client
```

However, the nsp vulnerability range (<= 99.999.99999 || <= 1.6.8) doesn't allow it.

**Comment by evilpacket** [comment]
Thanks for the report. We had not received reports back that it was addressed yet. I went ahead and updated the versions in the advisory.
