### ISSUE TITLE
A different exit code when the service is unavailable

### ISSUE THREAD

**Issue by majgis** [nodesecurity/nsp#111]
It would be nice if we could key off a different process exit code when the service is unavailable, unique to when there is a check request without a 200 response.

Would you take a PR that adds this enhancement?

**Comment by evilpacket** [comment]
I think it makes sense to deliver a different exit code based on if there was an error for whatever reason.

**Comment by majgis** [comment]
Ok, I will work on a PR and include as many error types as I can.

**Comment by HenrikJoreteg** [comment]
I would suggest this be an command line option passed to `nsp check`. Without this, it's difficult to include `nsp check` as a pass/fail requirement in CI. If the service goes down, would be nice if CI could keep flowing (perhaps with a warning) until it was back.

**Comment by HenrikJoreteg** [comment]
Perhaps `--ignore-service-interruptions` or something... just a thought. also, hi guys! :)

Overall, hope things are well, thanks for you work on nsp!

**Comment by nlf** [comment]
yeah ideally it would print a warning and exit with a 0 status code if the error isn't the user's fault (IMO)

**Comment by nlf** [comment]
and hi henrik! :wave:

**Comment by HenrikJoreteg** [comment]
yeah, that would work too, i just could see someone potentially wanting to be really strict about it too. I don't have strong preferences one way or the other, it'd just be great to have some way to have it not block CI for non-security related issues.

**Comment by mythmon** [comment]
Another helpful thing  would be to return a different error code for server failures vs security problems. ie: return 1 for security problems, 2 for server problems. That would make it easy to detect the issue and retry a couple times in CI.

**Comment by nlf** [comment]
i agree, that's a great idea!
