### ISSUE TITLE
Add support for custom reporters

### ISSUE THREAD

**Issue by pdehaan** [nodesecurity/nsp#112]
Ref: **Add checkstyle formatter** #110

Counter proposal for adding a bunch of custom formatters into the core **nsp** tool, we could add support for external formatters (sort of like how ESLint has their custom rules/configs, but you can also specify custom ones.

Possibly do something like publish your custom formatter (see #110) to npm as "nsp-formatter-checkstyle" and then set the `--output` flag to "checkstyle". nsp would continue to look for formatters internally (ie: "default", "summary", "json", "codeclimate", "none", etc), then check for a module named "nsp-formatter-${output}", and then fail (or fall back to default formatter) if a formatter was not found.

**Comment by evilpacket** [comment]
My initial gut reaction says this sounds good. Curious about what @nlf thinks

**Comment by nlf** [comment]
i like this idea. publishing as `nsp-formatter-XXXXX` makes perfect sense to me too, follows the eslint patterns roughly.

also completely eliminates the need for us to maintain output formatters we don't use ourselves, so i'm a big +1 here

**Comment by pigulla** [comment]
I've cobbled together an [implementation](https://github.com/pigulla/nsp/tree/third-party-formatters) to allow for third-party formatters ([compare view](https://github.com/nodesecurity/nsp/compare/master...pigulla:third-party-formatters?expand=1)) as well as a custom [Checkstyle formatter](https://github.com/pigulla/nsp-formatter-checkstyle). 

A couple notes:
 - I've left all the current formatters as built-in formatters. At least `codeclimate` is probably a candidate for extraction later on.
 - It's probably a good idea to exit with an error if a formatter could not be found (the current behaviour is to fall back to `default`). I didn't touch this to not break BC.
 - The formatters now also receive the filename as a third argument (not strictly needed for the Checkstyle report, but useful).

Let me know if this is roughly what you had in mind.

**Comment by pigulla** [comment]
Ant thoughts on this?

**Comment by evilpacket** [comment]
I haven't had a chance to check this out. This is due to client work and some other preparations I'm having to make to go out of town. Curious what others things, but I'll try and get to this this week for sure while I'm out at toorcamp and can relax :)

**Comment by nlf** [comment]
your implementation looks good to me, go ahead and submit it as a pull request and i'll look deeper. thanks!

**Comment by pigulla** [comment]
I don't mean to be pushy, but any particular reason this is not going forward?
