### ISSUE TITLE
Large npm-shrinkwrap file causes 400 error

### ISSUE THREAD

**Issue by betaorbust** [nodesecurity/nsp#123]
#### Overview
A large `npm-shrinkwrap` file causes the server to return:
```json
{
    "statusCode":400,
    "error":"Bad Request",
    "message":"Payload content length greater than maximum allowed: 1048576"
}
```

#### Repro steps:
- Generate a large shrinkwrap file (ours just hit 1.5MB)
- Run `nsp check`
- Error is returned
![image](https://cloud.githubusercontent.com/assets/921683/16823094/40cfd3ca-4916-11e6-8c01-0e2de98e7206.png)

**Comment by pdehaan** [comment]
@betaorbust Probably doesn't help, but you may be able to temporarily work around this [server config issue] by using something like [**shrinkydink**](https://github.com/nlf/shrinkydink) to remove some unncessary fields from your npm-shrinkwrap file before uploading to nsp.
Not sure if it'd remove 33% of your shrinkwrap file though so it'd fit under the current 1,048,476 byte limit.

**Comment by nlf** [comment]
if it's a full blown shrinkwrap to start with, shrinkydink should get it plenty small enough.

that said, i think it's reasonable for us to raise our limit a bit. i'll get that fix out for you this week sometime.

**Comment by micahr** [comment]
Just circling back, was this issue resolved?

**Comment by nlf** [comment]
i deployed the fix for this just now
