### ISSUE TITLE
Write GitHub bot to notify/update packages w/ vulnerable modules?

### ISSUE THREAD

**Issue by pdehaan** [nodesecurity/nsp#125]
Some random [stupid] idea I had while getting 3 emails from Node Security this morning while at an appointment.

After a new vulnerability is found and disclosed, what if somebody wrote a GitHub bot which filed an issue (or even a PR) which updates the package.json file with the latest/fixed version of the module. That way a module owner would just to review and merge the PR and then republish the module to npm.

But the beauty is that in this magical world, a person doesn't have to opt-in to NSP (or even know about it), the bot would simply trigger every time a new advisory is disclosed and them ~~spam~~ politely notify dozens or thousands of modules.

For example, 
1. https://nodesecurity.io/advisories/140 was disclosed this morning, wherein **mqtt@<=0.3.13** are vulnerable.
2. I think we can query npm's registry for modules which depend on a specific module (like **mqtt**) like so: https://registry.npmjs.org/-/_view/dependedUpon?group_level=3&startkey=[%22mqtt%22]&endkey=[%22mqtt%22,{}]&skip=0&limit=1000
3. We'd then have to query npm for each of those modules using something like [**get-package-json**](https://www.npmjs.com/package/get-package-json) to get the exact [dev]dependencies for the latest version, then maybe do some semver magic to see if the version specified in the latest published module is using a vulnerable version
4. File a bug or submit a PR with the updated package.json using the latest patched version of the vulnerable module.
### Cool story, bro, but it won't work:

Of course, dragons everywhere in that chain, but it may be good enough to notify a module owner that they're using a potentially vulnerable dependency. But the steps above don't account for:
1. Weird nested uber-repos, where the top level repository doesn't have a package.json file and it's in a nested subdirectory.
2. Somebody uses npm-shrinkwrap.json which would be out of sync now w/ package.json if we did a pull request.
3. If somebody was using semver ranges before in their package.json, would a PR still support that, or would you simply pin the dependency to the latest version and let module owners fiddle with it if they wanted to.
4. A package doesn't specify a repository field, so we'd have no way of knowing where to submit a bug/PR.
5. A package uses GitLab or something that isn't GitHub.
6. I'm sure many other weird sharp edges I haven't even considered with the ~15 minutes of thought I've put into this half-assed idea (or even third-assed).

---

**UPDATE:** Also, @dodekeract pointed out below that this may have some mid-air collisions w/ people that use greenkeeper to keep their dependencies up to date.

**Comment by guypod** [comment]
@pdehaan 
Maybe check out https://snyk.io/?
The Respond/Alert feature, which sends an email and a fix PR whenever a new vuln affects your dependencies, sounds like what you're looking for. 

More info: 
- https://snyk.io/blog/github-integration/
- https://github.com/integrations/snyk
- https://snyk.io/features#alert

**Comment by pdehaan** [comment]
Not exactly, I already subscribe to nsp updates, so I know when modules are vulnerable.
I'm thinking a service that notifies _every other module_ owner when a new vulnerability is found in their module would be 👌.

Currently when we run `nsp check` and find some dependency is vulnerable, we have to submit PRs in up-upstream projects to update dependencies, then wait for those people to merge, then publish to npm, then we can file bugs with upstream projects and do the same, then finally update our dependency.

**Comment by nlf** [comment]
@pdehaan we were just talking about this and we have some ideas. good suggestion!

**Comment by pdehaan** [comment]
Awesome, @nlf! I'll send you my address for the royalty checks.

**Comment by dodekeract** [comment]
Isn't this what greenkeeperbot already does?

**Comment by pdehaan** [comment]
@dodekeract Yes, and we use greenkeeper for some of our projects, but I was hoping that somebody [smarter than me] could build a bot that would patch _everybody else_ on npm, regardless of whether they use greenkeeper or snyk or nsp or even know about security advisories. Just some rogue bot which tries to patch all known issues (assuming there is a patched version available).

You'd be surprised (or probably not) how many people still install http://npm.im/fs and http://npm.im/path from npm, even though they don't do anything.

**Comment by pgarrison** [comment]
Someone wrote a bot to do this for a Java bug a few months ago: https://github.com/tobie/ua-parser/pull/516, https://github.com/wrml/wrml/pull/2, https://www.google.com/search?q=site%3Agithub.com+Upgrade+Apache+Commons+Collections+to+v3.2.2+by+gmlewis

**Comment by nlf** [comment]
for now, i think we're going to keep this as an opt-in feature within the platform. we're still on the fence about doing more than that, but i don't feel the need to keep this issue open while we continue our internal debates.
