### ISSUE TITLE
Scan Bower dependencies?

### ISSUE THREAD

**Issue by toddw** [nodesecurity/nsp#126]
Is it possible for NSP to scan an application's Bower dependencies?

**Comment by nlf** [comment]
currently, we do not scan bower dependencies and don't have a plan to. our focus is the node ecosystem and supporting another package registry would involve a rather large amount of work.

unfortunately, i'm going to close this one. if we do decide to support bower in the future we'll make a lot of noise about it though, so keep an eye out!
