### ISSUE TITLE
Filter vulnerabilities based on CVSS score

### ISSUE THREAD

**Issue by yannrouillard** [nodesecurity/nsp#129]
It would nice to have an option to filter issues processed and displayed based on CVSS score.

This would allow us to have a different `nsp` behavior depending on where the `nsp` tool is used in a CI pipeline.
For instance: we only display and stop with error for high and critical issues in the standard pipeline run at each commit, but we take all issues in account for daily code quality analysis.

**Comment by nlf** [comment]
i like this, interesting companion for #130

**Comment by mbaluda** [comment]
Already having the severity in the summary output would help filtering the results
