### ISSUE TITLE
document where list of advisories can be viewed

### ISSUE THREAD

**Issue by cdaringe** [nodesecurity/nsp#134]
hi all,

upon coming across `nsp`, i thought, "man, i need to bake this into my workflow!"

so, i got it running, and to validate that it was working, i wanted to test against a known vuln.  however, it wasn't clear to me where the CVEs are listed, and which `nsp` is testing against?

can you assist in the matter?  i googled `node CVEs` or something and i landed on https://snyk.io/vuln/.  i tested a few npm vulnerabilities there, such as https://snyk.io/vuln/npm:node-uuid:20160328, but nsp didn't catch it.

just curious how it all works.  i think we could beef the docs some?

thanks!  respectfully, @cdaringe

**Comment by pdehaan** [comment]
@cdaringe If you didn't find them yet, you can look through all the nsp advisories at https://nodesecurity.io/advisories/

**Comment by wraithgar** [comment]
Would it at least be worthwhile to add a link to the advisories in the readme right under the "about" section?

**Comment by cdaringe** [comment]
will submit a PR. thx

**Comment by cdaringe** [comment]
see #135
