### ISSUE TITLE
A security vulnerability that could be reported by nsp

### ISSUE THREAD

**Issue by JacksonGL** [nodesecurity/nsp#137]
The following npm package has Directory Traversal issue:
https://www.npmjs.com/package/bitty

This security vulnerability is similar to the issues that you reported here:
https://nodesecurity.io/advisories?search=directory+traversal

**Comment by nstarke** [comment]
Hi @JacksonGL , could you kindly use the following form to provide the vulnerability details? https://nodesecurity.io/report
Thanks for reaching out!

**Comment by JacksonGL** [comment]
@nstarke I just send the report. Let me know if you need more details.

**Comment by nlf** [comment]
this was turned into an advisory, so i'm going to go ahead and close the issue. thanks!
