### ISSUE TITLE
best-practice advice

### ISSUE THREAD

**Issue by roccomuso** [nodesecurity/nsp#141]
```json
{
  ...
  "scripts": {
     "test": "npm run ci_test && npm run security_check",
     "ci_test": "mocha --timeout=3000 tests/**/*.js",
     "security_check": "nsp check"
   }
}
```

Am I wrong saying this could be considered a node-based app best-practice? what's the best way to integrate it with mocha and CI environment?

**Comment by nlf** [comment]
this is certainly one way to do it, and is perfectly effective :)

the other way you could incorporate nsp in your CI process would be to use our platform at nodesecurity.io, from there you can register your repo to monitor pull requests in github automatically and we'll run the checks on our side and post the status back for you. free for open source, though we do charge for private repositories.
