### ISSUE TITLE
ValidationError: child "proxy" fails because ["proxy" is not allowed to be empty]?

### ISSUE THREAD

**Issue by sinedied** [nodesecurity/nsp#149]
When I try to use `nsp` I always have this error:
```
(+) ValidationError: child "proxy" fails because ["proxy" is not allowed to be empty]
```

I can reproduce it simply with:
```
$ npm init -f
$ npm i -S nsp
$ ./node_modules/.bin/nsp check
```

Nothing seems special about by npm config:
```
$ npm config list
; cli configs
user-agent = "npm/3.10.10 node/v6.9.4 darwin x64"

; userconfig /Users/noda/.npmrc
email = "<my_email>"
progress = false
registry = "https://registry.npmjs.org/"
strict-ssl = false

; globalconfig /usr/local/etc/npmrc
strict-ssl = false

; node bin location = /usr/local/bin/node
; cwd = /Users/noda/Desktop/nsp
; HOME = /Users/noda
; "npm config ls -l" to show all defaults.
```

I use OSX 10.12.1 (Sierra).

Any hints?

**Comment by nlf** [comment]
do you have a `.nsprc` file? either in your project's directory or your home directory?

**Comment by sinedied** [comment]
@nlf not at all

**Comment by nlf** [comment]
what happens if you run `unset HTTPS_PROXY` and try again?

**Comment by sinedied** [comment]
@nlf it works!
Thanks for the hint, but then this issue should be changed into a bug so the value can be checked for empty value without failing?
I constantly switch between proxies and never had an issue before using an empty value, AFAIK this is pretty standard.

**Comment by nlf** [comment]
Yup, it's a bug, just wanted to confirm I knew where the bug was :)

**Comment by nlf** [comment]
version 2.6.3 (which i just published) has this fixed, thanks for bringing it to our attention!
