### ISSUE TITLE
Errors with self-signed certs

### ISSUE THREAD

**Issue by rharris2825** [nodesecurity/nsp#153]
Every time I run nsp behind my proxy with a self signed cert I get the following error:

`(+) Error: Client request error: self signed certificate in certificate chain`

Is it / would it be possible to be able to specify a CA file or even just tell nsp to not use SSL?

**Comment by nlf** [comment]
not using ssl is definitely not an option, but we can certainly bundle the correct CA certificate with the cli tool to make sure this doesn't happen for operating systems which don't already have our root cert in place

**Comment by EnriqueCano** [comment]
I'm facing the same issue, it would be great to have a solution for this. Till then, I can't use this tool.

**Comment by evilpacket** [comment]
I tested this solution with node v6.11.3, v8.2.1, and v8.4.0

First I exported the `https_proxy` environment variable.
`$ export https_proxy=http://127.0.0.1:8080`

Then I ran nsp with the added environment variable [NODE_EXTRA_CA_CERTS](https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_file) pointing to my additional self signed ca cert in pem format. 
`$ NODE_EXTRA_CA_CERTS=/path/to/cacert.pem nsp check`

I believe this should work for you to use a corporate mitm proxy or whatever other proxy situation might be desired.
