### ISSUE TITLE
nsp check fails on 404 when gulp-zip is added to package.json

### ISSUE THREAD

**Issue by jakubzitny** [nodesecurity/nsp#154]
Hi there,

we're using NSP in our CI pipeline and `nsp check` started failing when we added `gulp-zip` dev dependency to our `package.json`. When I remove it, everything passes again.

```
(+) Debug output: "404 page not found\n"
(+) Error: Got an invalid response from Node Security, please email the above debug output to support@nodesecurity.io
```

I've sent an email as well. Is there anything else I can provide to help solve this issue?

We're using latest nsp `2.6.3`.

**Comment by gemal** [comment]
not sure it's related to gulp-zip since other also gets this error. See #155

**Comment by jakubzitny** [comment]
Thanks for noticing @gemal.

Closing with respect to #155.
