### ISSUE TITLE
nsp security check fails with 404

### ISSUE THREAD

**Issue by mjilugu** [nodesecurity/nsp#155]
Hi, this seems to be happening again. is it on your side?
```
(+) Debug output: "404 page not found\n"
(+) Error: Got an invalid response from Node Security, please email the above debug output to support@nodesecurity.io
```

**Comment by mjilugu** [comment]
It seems to happen intermittently but almost 85% of the time.

**Comment by ds-manish** [comment]
I have the same error....

**Comment by dragazor** [comment]
I have the same herror. Please help.

**Comment by jakubzitny** [comment]
Happens to us only with one recently added dependency (`gulp-zip`), so the possible problem might be with some sort of cache (where the old deps are cached properly, but the new one is not).

Also I've been having a lot of problems with loading https://nodesecurity.io, might be related.

**Comment by nlf** [comment]
sorry about that folks, we had a server in our load balancer that was flapping in shorter intervals than our health checks so this snuck by my monitoring for way too long. i've got it fixed now and bumped up the health check frequency so i should catch issues like this much quicker in the future.
