### ISSUE TITLE
List CVEs and references in --output json

### ISSUE THREAD

**Issue by jcrimp** [nodesecurity/nsp#156]
When running `nsp check --output json`, it would be great to list any associated `cves` listed, as well as any `references`. Currently the output does not include these fields.

CVEs and references can be found on the advisory's page, or via the API if you look up a specific advisory (https://api.nodesecurity.io/advisories/127), but it would be awesome to have them included initially in the CLI JSON output without having to do an additional request for each advisory returned. 

Ideally, I'd also like to be able to check an individual package at a specific version via the API (e.g. https://api.nodesecurity.io/check/gulp/3.9.1) and see the `cves` and `references` for each listed advisory.

In my case, I am attempting to compare vulnerabilities found via NSP, Snyk, and the Circl CVE search API, so getting CVEs for NSP advisories is key.

**Comment by jweinsteincbt** [comment]
The advisories.json downloaded from `npm run setup-offline` has cves listed. You could make a custom formatter which merged in that data. See #106 for downloading all advisories rather than just first 100.

**Comment by jweinsteincbt** [comment]
Could lookup by id or module_name
`console.log(require('./advisories.json').results.filter((adv) => adv.module_name=="dns-sync"))`
