### ISSUE TITLE
Add `quiet` to CLI

### ISSUE THREAD

**Issue by evilebottnawi** [nodesecurity/nsp#159]
Don't output anything if problems not found. BTW, most CLI programs don't output anything by default. Maybe change behavior on this. I can do PR if your accept.

**Comment by evilpacket** [comment]
A PR to add a quiet flag would be acceptable so long as the default behavior stays the same.

**Comment by marin-liovic** [comment]
I agree with this! This will enable nice integration when running multiple NPM scripts like `npm run nsp && npm run tests`

**Comment by nlf** [comment]
added in nsp@2.7.0
