### ISSUE TITLE
stderr used for both a report and actual errors

### ISSUE THREAD

**Issue by jborrey** [nodesecurity/nsp#161]
It would be good if stdout, instead of stderr, was where nsp would print in the event that execution succeeded but CVEs were found. Currently, stderr is used for both instances when nsp crashes and when nsp finds CVEs to report.

Both such cases also have an exit status of 1 and so there is no way to programmatically tell between these cases.

This differentiation will help with CI builds and automated checks.

**Comment by jborrey** [comment]
@nlf was there are reason to close this? If I submitted a PR would you consider it?

**Comment by nlf** [comment]
it's fixed in 3.0.0

Thanks,

Nathan

**Comment by jborrey** [comment]
Ah great - thank you!
