### ISSUE TITLE
requiresafe vs nsp

### ISSUE THREAD

**Issue by mkarvir** [nodesecurity/nsp#163]
Hi,
A new version of requiresafe -https://www.npmjs.com/package/requiresafe has not been published since last 2 years. Is it deprecated? How is requiresafe different than nsp? Thanks.

**Comment by evilpacket** [comment]
requiresafe is indeed deprecated (we should probably mark it as such). We consolidated them together a while back that improved upon the original version of nsp that was not very performant.
