### ISSUE TITLE
npm run setup-offline downloads only 100 advisories

### ISSUE THREAD

**Issue by AdamSaleh** [nodesecurity/nsp#166]
Looking at the resulting json, I can see:

```
{"total":307,"count":100,"offset":0,"results":[
```

and I can count only the first 100 advisories in the result list. This suggests that there is pagination turned on for https://api.nodesecurity.io/advisories, but there is no description in the readme to show how to set count or offset to get more advisories.

**Comment by munir131** [comment]
@AdamSaleh  You can use https://api.nodesecurity.io/advisories?offset=100 for more reacords.
