### ISSUE TITLE
auto-notify

### ISSUE THREAD

**Issue by shotlom** [nodesecurity/nsp#176]
1. This is definitely a cool tool. Thank you.
2. ```npx nsp check``` is definitely cool!
3. I don't really care if a package i don't own is using a package, is using a package, is using a package, which has a security vulnerability. 
4. What I care about is that all the package owners get auto-notified so they can patch appropriately.

Can we do this?

**Comment by evilpacket** [comment]
This is something we've given thought to in the past.

Generally we already work with the top level package owner to make sure it's fixed prior to releasing an advisory. Doesn't happen always but most of the time they address the issue or accept a pr to address it.

**Comment by evilpacket** [comment]
Right now projects can opt into monitoring / notification on nodesecurity.io (open source is free) so that's how they would find out. I don't think we'll proactively notify at this time for projects that haven't opted into communication from us.
