### ISSUE TITLE
Dependency check node analysis failing

### ISSUE THREAD

**Issue by javixeneize** [nodesecurity/nsp#177]
Hi

Im having problems with Dependency check, which uses nsp inside.

The error i am having from depcheck is as follows

[DependencyCheck] One or more exceptions were thrown while executing Dependency-Check
[DependencyCheck] Exception Caught: java.lang.ClassCastException
[DependencyCheck] Message: org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl cannot be cast to javax.json.JsonString
[DependencyCheck] Exception Caught: org.owasp.dependencycheck.analyzer.exception.AnalysisException
[DependencyCheck] Message: Could not perform NSP analysis. Invalid payload submitted to Node Security Platform.

Looking at the code, the error returned from NSP is a code 400

case 400:
                    LOGGER.debug("Invalid payload submitted to Node Security Platform. Received response code: {} {}",
                            conn.getResponseCode(), conn.getResponseMessage());
                    throw new AnalysisException("Could not perform NSP analysis. Invalid payload submitted to Node Security Platform.");

Any idea why nsp could return a 400 error?

Thanks

**Comment by evilpacket** [comment]
My gut says is going to be a malformed package.json (missing required fields) or shrinkwrap. Something in the payload is probably the wrong format.

Do you know what error you got back from nsp vs what dependency check tells you?

**Comment by javixeneize** [comment]
the problem is that depcheck by default checks all the package.json in the
folder instead of the main one. Thats sorted now

Thanks!

**Comment by evilpacket** [comment]
@javixeneize thanks for the follow up.
