### ISSUE TITLE
Support package-lock.json

### ISSUE THREAD

**Issue by waterfoul** [nodesecurity/nsp#179]
package-lock.json should have exactly the same format as npm-shrikwrap.json just under a different name (as of npm v5). It should be fairly easy to support the new file.

https://www.reddit.com/r/javascript/comments/6dgnnq/npm_v500_released_save_by_default_lockfile_better/di3mjuk/

**Comment by evilpacket** [comment]
Quick update on this. I just submitted a PR internally for the API to support package-lock.json. It should land in the API soon and then we'll get the various clients updated to support this.
