### ISSUE TITLE
nsp causes warning when running npm install with npm@5.3.0

### ISSUE THREAD

**Issue by arjenvanderende** [nodesecurity/nsp#181]
I have a project written in Node v8.2.1 and npm@5.3.0 that includes nsp as a devDependency. When running `npm install` the following warning is displayed`:

```
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
```

This is caused by nsp also publishing `npm-shrinkwrap.json` as part of the NPM package. When I remove this file or rename it to `package-lock.json` the warning disappears.

Is it necessary to include the shrinkwrap file as part of the published package? When I take a look at other packages, very few packages actually include a shrinkwrap- or lockfile. I'm not sure what's considered best practice here, since I expected most packages to include it.

Otherwise, is it possible to use a lockfile instead (same as #179?) by upgrading to npm@5? From the documentation I gather that this might be difficult (since npm@2 is still used), although I don't understand _why_.

**Comment by nlf** [comment]
closed in 2.8.0

**Comment by alijalbani** [comment]
just run yarn install again

**Comment by alijalbani** [comment]
deleting node_modules and running npm i worked for me

**Comment by rbar2** [comment]
@alijalbani saved my day 💯 🥇
