### ISSUE TITLE
Add support for deprecated packages

### ISSUE THREAD

**Issue by MovieStoreGuy** [nodesecurity/nsp#183]
Running version `2.7.0`, it does not report an error if a package is deprecated / not supported.

As a security advisory software, I believe this should be a key feature of nsp as it will force to devs to update versions of their packages or find a replacement for that deprecated package.

**Comment by evilpacket** [comment]
hmm. While I can see how deprecations can be a risk npm already shows output for deprecations when you npm i. 

As we can't easily and scalable maintain a list of alternatives for a package, so really all we would be able to do is output a message similar to what npm does.
