### ISSUE TITLE
Dev dependencies in Shrinkwrap

### ISSUE THREAD

**Issue by NicolasPelletier** [nodesecurity/nsp#185]
Good afternoon,

Latest version ( 2.8 ) has the development dependencies listed in the shrinkwrap file. This means that when I do `npm i` on my project that depends on NSP, I get "extraneous" dependencies because the production code does not need your development dependencies.

Would you be so kind and publish a new version ( 2.8.1 ? ) without development dependencies in the shrinkwrap ?

Many thanks.

**Comment by NicolasPelletier** [comment]
This was introduced here apparently: https://github.com/nodesecurity/nsp/commit/1d0b7b5ca145d30db062aa246f0bc2e3e3aa77f3#diff-36018a6a9e1de1798516799b84841318

**Comment by garyspencer** [comment]
Tuning in for updates.  Our team is also being affected by this issue.  We will have to stick with `~2.6.1` until further notice.

```
$ npm -v
    3.10.10
$ node -v
    v6.11.1
```

**Comment by evilpacket** [comment]
2.8.1 pushed without devDeps.
