### ISSUE TITLE
Question: license for the advisories data at https://nodesecurity.io/advisories

### ISSUE THREAD

**Issue by pombredanne** [nodesecurity/nsp#188]
Hi:
I reckon this package is Apache-licensed... What are the exact license terms for the data  at https://nodesecurity.io/advisories ? Do you provide a structured feed too for these?
I am looking at them for potential inclusion in an open source project at https://gitter.im/aboutcode-org/vulnerablecode together with many other aggregated data sources
Thanks!

**Comment by evilpacket** [comment]
Advisories and data obtained via our API are licensed per our TOS available at nodesecurity.io/tos

We've also donated our dataset to the node.js foundation. More information available here https://medium.com/lift-security/were-donating-the-node-security-project-to-the-node-js-foundation-1776e351394a

They will be providing a feed of data that's open to integration into tooling at some point in the future.

**Comment by pombredanne** [comment]
@evilpacket Thanks ++ for quick and clear answer!
