### ISSUE TITLE
nsp check error

### ISSUE THREAD

**Issue by ds-manish** [nodesecurity/nsp#189]
<img width="1012" alt="2017-09-21 10 47 29 am" src="https://user-images.githubusercontent.com/25601617/30679607-530f2eaa-9eba-11e7-880a-5c4403f6af24.png">

**Comment by evilpacket** [comment]
What's the issue? That you are seeing a duplicate finding?

**Comment by ds-manish** [comment]
Hi,

When i did `nsp check` I got this error. I could not figure it out.

**Comment by evilpacket** [comment]
I don't see an error. I see 2 findings for the tough-cookie regular expression denial of service vulnerability that was just published. We're waiting for the maintainers of the module to fix the issue or for a community member to contribute a fix.

**Comment by juancaacuna** [comment]
@ds-manish Create the file `.nsprc` a put it in the root folder.
Add this to the file:
```
{
  "exceptions": ["https://nodesecurity.io/advisories/525"]
}
```

**Comment by amalv** [comment]
In my case it's also saying that there is a vulnerability with `tough-cookie` version 2.3.3.

Which is the release that fixes this vulnerability.

It was fixed setting an exception as @juancaacuna suggested

**Comment by amalv** [comment]
It must already be fixed, it no longer says there is a vulnerablity with `tough-cookie` 2.3.3
