### ISSUE TITLE
Saving output to file

### ISSUE THREAD

**Issue by amitrai99** [nodesecurity/nsp#198]
Is there a way to save the output of the `nsp` command to a file?
I can't find any command line option to do that.

**Comment by evilpacket** [comment]
@amitrai99 is it possible to just redirect the output to a file like this? Currently all the output goes to stderr so normal redirection like `>` doesn't work. That's going to change very soon in 3.0.0

`nsp check &> output`

**Comment by amitrai99** [comment]
Checked the code and there is no command line option. Using @evilpacket  suggestion does work well enough for me. Closing the issue.
