### ISSUE TITLE
Does nsp support yarn lock file?

### ISSUE THREAD

**Issue by amitrai99** [nodesecurity/nsp#199]
More of a question than issue. Seems like nsp does not support yarn lock file. Is there any plan to support it in future.

**Comment by pdehaan** [comment]
There is an open PR for yarn.lock support at #187

**Comment by nlf** [comment]
i have a proposal regarding yarn that i posted here https://github.com/nodesecurity/nsp/pull/187#issuecomment-334624079

**Comment by amitrai99** [comment]
@nlf Thanks for responding to the query. I really liked the idea of creating a preprocessor. It really keeps the core nimble and allows for support of any new formats in future.

Closing this issue.
