### ISSUE TITLE
Internal Server Error make test fail

### ISSUE THREAD

**Issue by frangeris** [nodesecurity/nsp#203]
Hey guys, running check and getting this:

```sh
→ ./node_modules/.bin/nsp check
(+) Debug output: "Internal Server Error"
(+) Error: Got an invalid response from Node Security, please email the above debug output to support@nodesecurity.io
```

What's going on here?

Thanks

**Comment by nlf** [comment]
We're currently in the middle of some maintenance, I'm working hard on getting things finished so I can get services back up! Sorry for the interruption!
