### ISSUE TITLE
Gitlab Integration

### ISSUE THREAD

**Issue by neutraali** [nodesecurity/nsp#205]
Title - Are there any plans to support (self-hosted;private) [Gitlab](https://gitlab.com) -projects?

Would be nice to have badge-support for every master-commit, for example.

**Comment by evilpacket** [comment]
@neutraali At this point in time we do not have that on our roadmap. It would be pretty nice to have this support though.

**Comment by neutraali** [comment]
Thanks for the heads up @evilpacket - Consider this issue clarified and closed.
