### ISSUE TITLE
SyntaxError when using node 4.x

### ISSUE THREAD

**Issue by nicholascapo** [nodesecurity/nsp#208]
Commit 41f967f85b27f71832a1310a0854c6b48c9526d9 introduces a syntax error for node version 4.x

Minimal example:
```bash
$ docker run -it node:4.8.3 /bin/bash -c 'npm install -s --no-progress -g nsp && nsp --version'
/usr/local/bin/nsp -> /usr/local/lib/node_modules/nsp/bin/nsp
[...]
/usr/local/lib/node_modules/nsp/commands/check.js:63
  const { shrinkwrap, packagelock } = args;
        ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at Object.require (internal/module.js:12:17)
    at /usr/local/lib/node_modules/nsp/node_modules/yargs/node_modules/require-directory/index.js:76:17
    at Array.forEach (native)
    at requireDirectory (/usr/local/lib/node_modules/nsp/node_modules/yargs/node_modules/require-directory/index.js:59:24)
```

**Comment by evilpacket** [comment]
As per [our announcement](https://medium.com/node-security/announcing-nsp-3-0-0-bc5e61b33509) we're currently only support node.js 6.x and beyond with the 3.x release

To support 4.x you will want to use the 2.x release line, which I believe the last release was 2.8.1

**Comment by nicholascapo** [comment]
Thanks, as it happen we just upgraded to node 8 a few days ago.
I only found this because we have a few lagging branches.

Can the info from that blog post be added to the Readme?

**Comment by nicholascapo** [comment]
Also note that node 4.x is officially supported until April 2018: https://github.com/nodejs/Release

**Comment by nlf** [comment]
we're aware that 4.x is still supported, however only in a maintenance fashion. we elected to develop the new release of nsp based on the active lts, which at the time of its writing was 6.x (i should note that 8.x is actually in active lts now as well, though we plan to continue to target 6.x until it reaches the maintenance release phase in april of 2018)
