### ISSUE TITLE
What happened to open issues?

### ISSUE THREAD

**Issue by lumberj** [nodesecurity/nsp#40]
It looks like there were several open issues, one of which I was recently following:
http://webcache.googleusercontent.com/search?q=cache:OKM57KEzSD8J:https://github.com/nodesecurity/nsp/issues/83+&cd=1&hl=en&ct=clnk&gl=us

Closing the issues with an explanation would have been clearer than deleting them.

**Comment by evilpacket** [comment]
@lumberj the entire client has been re-written. The repository has been replaced with a completely new version. Details here. https://blog.liftsecurity.io/2015/10/29/announcing-node-security-2.0

**Comment by evilpacket** [comment]
We'll have the new API up shortly and publish nsp@2.0.0 (possibly before Monday)
