### ISSUE TITLE
docker image build command incorrect

### ISSUE THREAD

**Issue by olivierba** [nodesecurity/nsp#42]
Hi,
The following command is not working: docker build -t codeclimate/codeclimate-nodesecurity 
there's no codeclimate-nodesecurity repository. On the other hand codeclimate/codeclimate-requiresafe exists.
It's likely that when renaming requiresafe to nodesecurity you also modified this command and did not update the name on docker.

**Comment by nlf** [comment]
codeclimate actually builds the container for us, since it's their repository. @mrb can you kick off a build under the new name?

**Comment by jpignata** [comment]
@nlf Sure, we can do that. Looks like there's a couple of changes to the codebase that impact our interoperability. I'm going to open a pull for your review to try to address them first. Once we work through those we can make the rename changes on our side and push the image.

**Comment by jpignata** [comment]
@nlf In testing I found one further issue related to that refactor and error conditions. Looks like if a user hasn't run shrinkwrap, they'd get back:

```
Debug output: %jundefined`
{}
```

I have another pull to address: https://github.com/nodesecurity/nsp/pull/53. Once that's merged in I can push a new image and update our CLI.

**Comment by jpignata** [comment]
I pushed up the new image and tested it against our latest CLI release. Let me know if you see any issues.

**Comment by nlf** [comment]
closing this since i think we're good here
