### ISSUE TITLE
transitive dependencies with vulns have truncated paths with npm3

### ISSUE THREAD

**Issue by DonutEspresso** [nodesecurity/nsp#44]
Due to npm3's flattening, transitive dependencies that have vulnerabilities are now reported as direct dependencies:

https://twitter.com/ReBeccaOrg/status/661386106135425024

Might be worth checking with npm to see what they have exposed that would let us reconstruct the dependency tree. This output was generated using the new client's `nsp check` against a shrinkwrapped file.

**Comment by evilpacket** [comment]
@DonutEspresso thanks for the report. We'll have to discuss this more and see what we can do. We have the ability to generate a dep tree based on the package that is also provided but it's possible for them to be out of sink. Unlikely but the shrinkwrap takes dominance when installing. Not sure what we will do but will keep this open for tracking.

**Comment by DonutEspresso** [comment]
Agreed, shrinkwrap should most definitely take precedence when available. I'm not sure that nsp behavior needs to change, rather just the addition of some metadata in the report would be enough.

Since the dependency tree is basically lost in the new shrinkwrap file, it sounds like we'd have to verify shrinkwrap validity before regenerating the tree. Maybe regenerate it, then do a diff? It should be deterministic in any case, or if npm provides some first class facility to do said validation. If it's valid, you can then safely walk the dependency tree, and attach the full module tree to the report. If it's not valid, then simply noting 'N/A' or 'shrinkwrap invalid' is probably enough to point the developer in the right direction. Just some thoughts from my perspective, though it's possible I've missed something.

**Comment by evilpacket** [comment]
Just a quick update on this issue. @nlf has made a lot of progress this last week fixing this and now it's internal testing. It certainly wasn't an easy issue to solve. 

In the process we got some amazing performance gains on processing package.json files as well. Hopefully we will have a fully tested and available fix for this next weekish.

**Comment by DonutEspresso** [comment]
Thanks! Appreciate the hard work on this - hope you all didn't work too much over Thanksgiving. :)

**Comment by nlf** [comment]
most of this should be resolved as of yesterday (12/30/15), if you're still having issues please reopen this issue. if you can provide a package.json/npm-shrinkwrap.json that reproduces the problem that would also be hugely helpful.
