### ISSUE TITLE
Add ability to check global modules for vulnerabilities

### ISSUE THREAD

**Issue by pdehaan** [nodesecurity/nsp#53]
Not sure if there is an easy way to scan globally installed modules for known vulnerabilities, but that'd sure be neat.

I can get as far as `$ npm ls -g --json` not sure if that outputs a shrinkwrap compatible format or if we'd need some converter or some other way to scan those modules.

**Comment by evilpacket** [comment]
Moved this issue over to requiresafe internally. Closing as we will be deprecating nsp in favor of requiresafe
