### ISSUE TITLE
504 Gateway Issue

### ISSUE THREAD

**Issue by joeycozza** [nodesecurity/nsp#56]
For the past 24 hours when running `nsp check` it gives this response.
```
Debug output: 504 Gateway Time-out The server didn't respond in time.
Error: Got an invalid response from Node Security, please email the above debug output to support@nodesecurity.io
```
When I tried sending an email to support@nodesecurity.io I got this email response.

```
Delivery to the following recipient failed permanently:
support@nodesecurity.io
Technical details of permanent failure:
Google tried to deliver your message, but it was rejected by the server for the recipient domain  
 nodesecurity.io by aspmx.l.google.com. [2607:f8b0:4003:c0a::1a].
The error that the other server returned was:
550-5.1.1 The email account that you tried to reach does not exist. Please try
550-5.1.1 double-checking the recipient's email address for typos or
550-5.1.1 unnecessary spaces. Learn more at
550 5.1.1  https://support.google.com/mail/answer/6596 e8si4862694oej.58 - gsmtp
```

Any word?

**Comment by latentflip** [comment]
Hey @joeycozza, I'll prod the nsp folks when they're awake about the email thing. Are you running the latest version of nsp (~2.0.0), we've upgraded a bunch of stuff recently.

If you have done that, is it possible you're project is very large (i.e. has a lot of dependencies)? Could be one cause of timeouts potentially?

**Comment by evilpacket** [comment]
@joeycozza I just tried `nsp check` on a small project and it worked fine. It's possible @nlf did something this morning causing things to pop back up when that issue rolled in.

Does the project you are checking have a shrinkwrap or only a package.json?

**Comment by joeycozza** [comment]
I am on 2.0.0 and my package is quite large. I tested nsp check on some smaller projects and it worked fine.

I only have a package.json.

What are some good options I could look at for nsp checking my large project?

**Comment by nlf** [comment]
i suspect your large package.json caused an actual timeout. if it's possible for you to create a shrinkwrap and check against that, it will be *much* faster. in the mean time i can adjust timeouts on our end.

i'll make sure that email works right now.

**Comment by joeycozza** [comment]
It is funny, i couldn't shrinkwrap because of gulp-nsp.  Once I removed that dependency and deleted the gulp-nsp node_module, I was able to shrinkwrap.

And you were correct. `nsp check` with the shrinkwrap was MUCH faster.  Thanks for help.

I'll be doing some testing with shrinkwrap and gulp-nsp and put any issues I find over there.

**Comment by nlf** [comment]
is there any chance you can send us your package.json for testing purposes? you can change the name and remove any private modules, really we just need the dependency list.

**Comment by nlf** [comment]
if you can, send it to the support@nodesecurity.io email. if not, no worries we can come up with some tests on our end.

**Comment by joeycozza** [comment]
I'm editing it a tiny bit right now.
