### ISSUE TITLE
Offline mode doesn't seem to work

### ISSUE THREAD

**Issue by reedloden** [nodesecurity/nsp#62]
Forgive me if it's something stupid, but I cannot get `nsp`'s offline mode to work at all.

```
| => ls -lah ../advisories.json
-rw-r--r--  1 reed  reed    63K Nov 27 18:12 ../advisories.json
________________________________________________________________________________
| => nsp check --offline
(+) Error: Offline mode requires a local advisories.json
```

From https://github.com/nodesecurity/nsp/blob/4e1c3c1c1e12d29a96bdb84660f027d88630fd33/lib/check.js#L113-L120, it looks like that should work fine, but it doesn't. I've also tried putting the `advisories.json` file in the current working directory, but that doesn't work either.

Any assistance would be appreciated.

**Comment by evilpacket** [comment]
@reedloden thx for the report. @nlf initially built this to support the codeclimate engine and so there may be situations in this doesn't work. We are all out until Monday but will take a look at this as soon as we can and get to the root of it.

**Comment by evilpacket** [comment]
I did a bit of debugging and I think it has to do to the path location of the advisories.json. it's going to be relative to the installed binary, depending on how nsp is being used. 

Guessing it's setup to work just with the codeclimate build and not taking into account other uses. We could make this more configurable like what @reedloden did in https://github.com/nodesecurity/nsp/pull/61 or something similar.

Will dig more later.

**Comment by reedloden** [comment]
Any update on this, @evilpacket?

**Comment by evilpacket** [comment]
I confirmed that offline mode does in fact work. It requires that the advisories.json file be in the location of wherever nsp module is installed.

I'll update the docs and I'll test your pr for a configurable path

**Comment by evilpacket** [comment]
Updated docs.
