### ISSUE TITLE
Question: Should the dependencies not be checked

### ISSUE THREAD

**Issue by cramhead** [nodesecurity/nsp#63]
I ran grep on the output of `npm list` with package names marked as having vulnerabilities and got
│ ├─┬ uglify-js@2.5.0
│ │     └── sigmund@1.0.1
│ │ │   ├─┬ tar@2.2.1
│ │ │   └─┬ tar-pack@2.0.0
│ │ │     │   └── sigmund@1.0.1
│ │ │     ├─┬ tar@0.1.20
│ │ │     └── sigmund@1.0.1
│ │ └─┬ uglify-js@2.4.24
│   │ └─┬ uglify-js@2.2.5
│   ├─┬ uglify-js@2.4.24
When I ran `nsp check` it said there where no vulnerabilities. The vulnerability in uglify-js is fixed in 2.6, but you can see that some of my dependencies include an older version, i.e. 2.4.24 and 2.2.5. 
I'm assuming that it didn't find the vulnerabilities because uglify-js is not in my package.json and is only there as a result of another package bringing it in. 
Is it because they were brought in via a devDependency?
Is it not reasonable to check all dependencies?
What about devDependencies should they be checked?

**Comment by evilpacket** [comment]
@cramhead We found a nasty little bug yesterday afternoon and have been working to fix it that may be related to this. We have a deploy going out shortly for the api that may address this.

Would you mind sharing your package.json / npm-shrinkwrap.json with me so we can test

> Is it because they were brought in via a devDependency?
We don't check dev dependencies unless you use shrinkwrap and include those in your shrinkwrap

> Is it not reasonable to check all dependencies?
Yes we do check the tree all the way down if we can. I think you're running into the bug we are working on right now.

> What about devDependencies should they be checked?
We plan to have this as a flag in the future.

**Comment by cramhead** [comment]
Hi Adam,

Sure, package.json below. Thoughts on the questions? I’m sure others will want to know too.

{
  "name": “test",
  "version": "1.0.0",
  "description": “test",
  "main": "server.js",
  "scripts": {
    "test": "karma start",
    "start": "node server.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "angular": "1.4.7",
    "angular-animate": "1.4.7",
    "jquery": "2.1.4",
    "rangy": "1.3.0",
    "textangular": "1.4.6",
    "blueimp-file-upload": "9.11.2",
    "blueimp-load-image": "1.14.0",
    "fileapi": "2.0.17"
  },
  "devDependencies": {
    "angular-mocks": "1.4.7",
    "body-parser": "^1.14.1",
    "chai": "^3.4.1",
    "express": "^4.13.3",
    "grunt": "^0.4.5",
    "grunt-contrib-clean": "^0.6.0",
    "grunt-contrib-concat": "^0.5.1",
    "grunt-contrib-copy": "^0.8.2",
    "grunt-contrib-uglify": "^0.10.1",
    "grunt-contrib-watch": "^0.6.1",
    "grunt-execute": "^0.2.2",
    "grunt-html2js": "^0.3.5",
    "grunt-include-replace": "^3.2.0",
    "grunt-karma": "^0.12.1",
    "grunt-ng-annotate": "^1.0.1",
    "grunt-sass": "^1.1.0",
    "grunt-ts": "^5.1.1",
    "karma": "^0.13.15",
    "karma-chai": "^0.1.0",
    "karma-chrome-launcher": "^0.2.1",
    "karma-firefox-launcher": "^0.1.7",
    "karma-ie-launcher": "^0.2.0",
    "karma-mocha": "^0.2.0",
    "karma-nested-reporter": "^0.1.3",
    "karma-ng-html2js-preprocessor": "^0.2.0",
    "karma-phantomjs-launcher": "^0.2.1",
    "karma-sinon-chai": "^0.2.0",
    "load-grunt-tasks": "^3.3.0",
    "mocha": "^2.3.4",
    "open": "^0.0.5",
    "phantomjs": "^1.9.18",
    "request": "^2.67.0",
    "save": "^2.1.1",
    "serve-static": "^1.10.0",
    "sinon": "^1.17.2",
    "tslint": "^2.5.1"
  }
}

**Comment by evilpacket** [comment]
Thanks. We'll test it out and get it figured out and let you know what we find. Sorry for the trouble. Turns out this is a hard problem :)

**Comment by evilpacket** [comment]
@cramhead 

The reason vulnerabilities weren't found in your situation was that we aren't checking devDependencies right now. We are going to leave this issue open and treat it as an open ticket to add a flag to force checking of devDependencies. If you use npm-shrinkwrap and include devDependencies these would be checked.

@nlf and I are also working on a document to describe how we are checking package and shrinkwraps, and what we don't check and update that as we add features or change behavior so it's clear as to what you should expect.

**Comment by cramhead** [comment]
I ran `npm shrinkwrap —dev` and it did list the vulnerable packages. 

This is a useful tool. Thanks for the quick response and making the tool

Do you think it may be integrated in npmjs.org <http://npmjs.org/> someday so that people are aware of problems before using the package and developers who use a dependency could be made aware of the problem?

**Comment by nlf** [comment]
i'm going to go ahead and close this, since i think your question is answered. do feel free to reopen it or open a new issue if you have any more questions though
