### ISSUE TITLE
Packages themselves aren't checked, only dependencies

### ISSUE THREAD

**Issue by pcorey** [nodesecurity/nsp#67]
When running `nsp check` on a clone of a vulnerable package, only the package's dependencies are checked for vulnerabilities, not the package itself.

For example, watch what happens when we check a vulnerable version of `send`:

~~~
git clone https://github.com/pillarjs/send.git
cd send/
git checkout tags/0.1.4
nsp check
~~~

Returns no vulnerabilities. Ideally, it should return two vulnerabilities found for this version of `send`.

**Comment by evilpacket** [comment]
@pcorey thanks for reporting this. This is a known issue internally that we plan to address. Just didn't think it would come up so quickly :) We'll leave it open as a reminder to see how we can address it in the API.

**Comment by pcorey** [comment]
Awesome! Good to know you guys are working on it.

**Comment by nlf** [comment]
this is fixed, thanks for letting us know

**Comment by pdehaan** [comment]
Has this change been released yet? Any chance we can get a new **nsp** version published to npm with this fix?

**Comment by nlf** [comment]
the fix was in the API rather than the client, so a new release shouldn't be necessary. let me know if you're still seeing issues though

**Comment by pdehaan** [comment]
Weird. I just did an `npm i moment@2.0.0 -D` and ran nsp and got no errors. I then added it as a regular dependency with `npm i moment@2.0.0 -S` and saw the nsp errors. I'll keep poking at it and make sure I didn't mess something up.

**Comment by nlf** [comment]
this issue wasn't about dev dependencies, but rather checking the module itself (i.e. if you were to clone moment's git repo and run nsp check from that clone). checking dev dependencies is still on our radar and isn't complete yet

**Comment by pdehaan** [comment]
Oh, in that case, nevermind. I misread the bug and am just making noise.
Move along, nothing to see here! :smoke_bomb:
