### ISSUE TITLE
Allow comments in .nsprc

### ISSUE THREAD

**Issue by wolfgang42** [nodesecurity/nsp#68]
I can't find the code where `.nsprc` is read, but it appears to be a JSON-format file, which doesn't allow comments. It would be really useful to be able to explain *why* we're ignoring a vulnerability, directly in the file. (`git blame` works, but requires an extra step.)

The easiest way I can think of is to make .nsprc a YAML file, to maintain backwards compatibility.
Example:
```yaml
exceptions:
  # These exceptions are for jade > transformers > uglify-js, which we don't use so it's safe to ignore.
  # https://github.com/ForbesLindesay/transformers/issues/52
  - https://nodesecurity.io/advisories/39 # uglify-js: Regular Expression Denial of Service  
  - https://nodesecurity.io/advisories/48 # uglify-js: Incorrect Handling of Non-Boolean Comparisons During Minification   
```

**Comment by nlf** [comment]
We use [rc](https://github.com/dominictarr/rc) for configuration loading, which supports comments in json. See https://github.com/dominictarr/rc#formatted-as-json
