### ISSUE TITLE
commands are not executed

### ISSUE THREAD

**Issue by jkaizer** [nodesecurity/nsp#69]
Just installed nsp. When running `nsp audit-package` or `nsp version` no results are printed. Even with the version command.

Debugging the code shows that the action callback in the `celery.option` is never called.

Do others have the same issue?

**Comment by evilpacket** [comment]
I just did a fresh install on 0.10.36 and I'm getting the same result. I'm guessing one of our dependencies changed out from under us. :/

**Comment by evilpacket** [comment]
@jkaizer I pushed a version to master with a npm-shrinkwrap.json that has the proper and working dependencies. We decided internally that we are going to dump celeri as it's way to complex and isn't being actively maintained well enough.

Can you install nsp@1.0.1 and let me know if it's resolved for now?

**Comment by jkaizer** [comment]
Yes, this works!

Thanks very much for the quick response.
