### ISSUE TITLE
False positive with certain dependencies on audit-package

### ISSUE THREAD

**Issue by panozzaj** [nodesecurity/nsp#71]
First, wanted to say thank you for working on this project, I think is very helpful for the Node community to have something like this to detect known vulnerabilities. Thanks!

I currently have trouble validating a package.json with bower@1.4.0 (released yesterday). I think this is possibly a larger problem, so wanted to reach out.

It has to do with bower's package.json containing a dependency for bower-registry-client that is "^0.2.1", which in reality resolves to "0.2.4". bower-registry-client@0.2.1 contains a known vulnerability in its dependencies, but bower-registry-client@0.2.4  does not (at this time.)

Here is my current replication process:

```
$ mkdir test
$ cd test
$ npm init
...
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
Is this ok? (yes) yes

$ npm install bower --save
... installs bower@1.4.0

$ npm install nsp --save-dev
... installs nsp@1.0.1

$ npm list bower nsp
test@1.0.0 /Users/anthony/Documents/dev/test
├── bower@1.4.0
└── nsp@1.0.1

$ nsp audit-package
Name  Installed  Patched  Vulnerable Dependency
qs      0.6.6     >= 1.x  test@1.0.0 > bower@1.4.0 > bower-registry-client@0.2.1 > request@2.27.0 > qs@0.6.6

$ echo $?
1

$ npm shrinkwrap
npm WARN shrinkwrap Excluding devDependency: nsp
wrote npm-shrinkwrap.json

$ nsp audit-shrinkwrap
No vulnerable modules found

$ echo $?
0
```

So, audit-shrinkwrap works, but audit-package does not. I am guessing this is because `npm shrinkwrap` writes the actual resolved versions and audit-shrinkwrap looks at those versions. However, audit-package cannot currently realize that bower-registry-client "^0.2.1" is fine, since it points to 0.2.4.

Does this seem like the right thing? Maybe I am missing something with NPM or how I need to declare packages.

I wonder if you can advise on this. Thanks!

**Comment by evilpacket** [comment]
Thanks for pointing this out and we will certainly have to make that clear in the documentation.

For auditing packages we take the approach of returning the package version that is the greatest that matches the semver string in the package.json which is exactly what you pointed out. 

If you are using shrinkwrap you should always use `nsp shrinkwrap` vs package because npm will install the versions specified in shrinkwrap. That way you are auditing the exact same versions that you would be installing.
