### ISSUE TITLE
nsp failing its own audit :)

### ISSUE THREAD

**Issue by KyleAMathews** [nodesecurity/nsp#72]
```
Name    Installed  Patched  Vulnerable Dependency
semver    3.0.1    >=4.3.2  page-server@1.0.12 > nsp@1.0.1 > semver@3.0.1
semver    2.3.2    >=4.3.2  page-server@1.0.12 > nsp@1.0.1 > silent-npm-registry-client@0.0.1 > npm-registry-client@0.2.31 > semver@2.3.2
```

**Comment by pdehaan** [comment]
Filed the upstream **silent-npm-registry-client** issue as https://github.com/juliangruber/silent-npm-registry-client/issues/4.

**Comment by marcellodesales** [comment]
Hi there, the issue at https://github.com/juliangruber/silent-npm-registry-client/issues/4 has been merged to https://github.com/juliangruber/silent-npm-registry-client/commit/16ad82381d219a90e6f2b1286771c065f21adc1a

Could you please rebuild NSP with the latest?

**Comment by FGRibreau** [comment]
:+1:
