### ISSUE TITLE
How do I give feedback?

### ISSUE THREAD

**Issue by ralphtheninja** [nodesecurity/nsp#73]
I noticed the other day that there were some problems with `hawk` and `nsp` reports that `hawk@4.1.1` should be used (https://nodesecurity.io/advisories/77). However, it seems that this was also fixed in `hawk@3.1.3`.

Now to my question. What is the process of updating you about changes like this?

**Comment by ralphtheninja** [comment]
See discussion in https://github.com/request/request/pull/1891

**Comment by evilpacket** [comment]
Email report at nodesecurity.io is the best. We can hash this one out here. Thanks for the heads up. We'll make it easier to report issues on advisories in the future.

**Comment by ralphtheninja** [comment]
> Email report at nodesecurity.io is the best. We can hash this one out here. Thanks for the heads up. We'll make it easier to report issues on advisories in the future.

:+1: Would be nice if you wrote something about that in the `README`.

**Comment by ralphtheninja** [comment]
Re-opening. Maybe you can ping me on this issue when this has been resolved?

**Comment by evilpacket** [comment]
I've updated the advisory to include the proper versions that are fixed / vulnerable. I've also updated the readme to include some directions on where to submit advisory updates.

**Comment by ralphtheninja** [comment]
> I've updated the advisory to include the proper versions that are fixed / vulnerable. I've also updated the readme to include some directions on where to submit advisory updates.

Rock n roll!
