### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by plynchnlm** [nodesecurity/nsp#75]
I just added nsp to a new project, and got "no known vulnerabilities".  I then went to an old project to which I had needed several exceptions in .nsprc, removed the .nsprc file, ran nsp and got "no known vulnerabilities".  I should have gotten several errors.

I think I have seen this happen before, where for a while nsp reported no vulnerabilities, and then suddenly started reporting them again.

**Comment by evilpacket** [comment]
Yes this still works. You can always verify that things are working for you with our [demo repo](https://github.com/nodesecurity/demo) if you suspect something is amiss. That should always work.

What I suspect is happening is that we updated or clarified some vulnerable versions / semver ranges that now excluded the versions you are running. If you can share what the exceptions were I can research a bit more to see exactly what might have occurred or if we have a larger bug at hand.

**Comment by plynchnlm** [comment]
One advisory I was excluding in my .nsprc was https://nodesecurity.io/advisories/31, against semver < 4.3.2.  My npm-shrinkwrap.json file contains these lines:

```
        "semver": {
          "version": "2.3.2",
          "from": "https://registry.npmjs.org/semver/-/semver-2.3.2.tgz",
          "resolved": "https://registry.npmjs.org/semver/-/semver-2.3.2.tgz"
        },
```
But even when I move .nsprc to something else, I get "No known vulnerabilities found" from "grunt nsp".
