### ISSUE TITLE
nsp fails to report advisory 31 for semver 2.3.2

### ISSUE THREAD

**Issue by plynchnlm** [nodesecurity/nsp#76]
I created a small test project with the following package.json
{
  "name": "test_nsp",
  "version": "0.0.0",
  "description": "",
  "dependencies": {},
  "devDependencies": {
    "grunt": "^0.4.5",
    "grunt-cli": "^0.1.13",
    "grunt-nsp": "~2.1.2",
    "semver": "^2.3"
  }
}

I am using node version v0.10.40 and npm version 3.3.9.  npm install puts version 2.3.2 of semver in node_modules/semver, which should be covered by advisory #31.  I ran npm shrinkwrap -dev, and confirmed that 2.3.2 of semver appears in npm-shrinkwrap.json.  However, grunt nsp reports "No known vulnerabilities found" as does "node_modules/grunt-nsp/node_modules/nsp/bin/nsp check ./npm-shrinkwrap.json".

**Comment by evilpacket** [comment]
@plynchnlm can you email baldwin@andyet.net both your package and shrinkwrap and I can create test cases and figure out what is going on?

**Comment by evilpacket** [comment]
@plynchnlm no need I think I can replicate

**Comment by evilpacket** [comment]
@plynchnlm this is a valid bug. Not sure quite what is going on but were looking into it.

**Comment by plynchnlm** [comment]
Thanks!  I'm glad to here it is not just me.

**Comment by evilpacket** [comment]
Ok, I'm pretty sure this has to do with dev dependencies not being checked. when i move it from dev to regular dep it finds it jsut fine. Now I'm checking with shrinkwrap

**Comment by plynchnlm** [comment]
I'm not sure how to interpret your statement, but IMO dev dependencies should be checked, because they are often involved in building files/packages used in production, even if they are not used directly in production, so a flaw in a dev dependency could affect production.

**Comment by nlf** [comment]
yeah, we talked about it today and i think you're right. there's been enough confusion around the behavior regarding devDependencies that we'll be making changes to check them by default. give us a little time, but we'll get it going in the next couple of weeks.

**Comment by jedrichards** [comment]
Just adding a :+1: for checking dev deps. This was just confusing me ... I was getting a warning for a dep on one project, but not another, only diff being it was a dev dep in one, and not the other.

In my case it was missing vulnerabilities in a shrinkwrap file created with `npm shrinkwrap --dev`.

**Comment by nlf** [comment]
closing in favor of #87
