### ISSUE TITLE
Who uses nsp?

### ISSUE THREAD

**Issue by evilpacket** [nodesecurity/nsp#77]
If your company is using nsp in production, please let us know who are you so we can mention you in the README and on the new site we are putting together!

**Comment by betaorbust** [comment]
We have every engineer pushing code for [netflix.com](http://neflix.com) running NSP as part of our git pre-push hook.

**Comment by joeycozza** [comment]
At Grow ([grow.com](grow.com)) we use gulp-nsp in our build process and are warned of any issues every time we start up our app locally.

**Comment by reedloden** [comment]
[HackerOne](https://hackerone.com) uses NSP as part of our CI/CD automation.

**Comment by joeybaker** [comment]
[Getable](https://www.getable.com) has `nsp` built into our CI.

**Comment by cullophid** [comment]
We are using nsp for all our node micro services socialfinance.org.uk

**Comment by garrows** [comment]
At [Console.to](http://console.to) we use it before every publish.

**Comment by pdehaan** [comment]
Using (and loving) it for several projects at Mozilla.

**Comment by ralphtheninja** [comment]
We're using it at [nowsecure.com](https://www.nowsecure.com/)

**Comment by danillouz** [comment]
We at [Crowdynews](http://www.crowdynews.com) are using it as part of our automated testing chain.

**Comment by jreading** [comment]
We are using this at [Morningstar](http://www.morningstar.com/) in our main application framework on a dozen products.

**Comment by manuel-reil** [comment]
We at [alyne.com](https://www.alyne.com) are using it regularly, not yet embedded in automated testing.

**Comment by shamasis** [comment]
We have included as part of our CI - https://www.getpostman.com/

**Comment by chetanddesai** [comment]
We use it at Intuit for checking our dependencies during builds.

**Comment by doug-wade** [comment]
We use it at [Redfin](https://www.redfin.com/) for checking our private node_modules during every build. Vulnerabilities break the build.

**Comment by PitmanPete** [comment]
At [signstix.com](http://www.signstix.com) nsp is part of our build process.  Security is good, right?

**Comment by jborrey** [comment]
coinbase.com uses it for all node services deployed to production.

**Comment by pcactr** [comment]
Used in US Army for software assurance

**Comment by evilpacket** [comment]
Thanks everyone for using nsp. <3 

Going to close this, but if you happen to find it, please add yourself below.
