### ISSUE TITLE
Delay in picking up .nsprc change

### ISSUE THREAD

**Issue by jlamondw** [nodesecurity/nsp#82]
I'm noticing some behavior with `nsp check` that I haven't seen before.  If I have a package.json file that looks like this:

    {
      "name": "nsptest",
      "version": "1.0.0",
      "description": "",
      "main": "index.js",
      "dependencies": {
        "jshamcrest": "^0.7.0",
        "nsp": "^2.2.1"
      },
      "devDependencies": {},
      "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1"
      },
      "author": "",
      "license": "ISC"
    }

and I run `nsp check` I get a warning about the jshamcrest vulnerability.  If I add a .nsprc file that looks like this:

    {
      "exceptions": ["https://nodesecurity.io/advisories/53"]
    }

and run `nsp check` I still see the vulnerability.  **Eventually**, say after a few minutes I eventually get a response that No known vulnerabilities have been found indicating the exception has been picked up.

If I remove the file and rerun `nsp check` I initially see "no known vulnerabilities" but **eventually** it will tell me that it finds the jshamcrest vulnerability.

**Comment by nlf** [comment]
thanks for the report.

the reason for this is because we cache check results on the server side, but we neglected to account for exceptions as part of the cache. i'll get it fixed.

**Comment by nlf** [comment]
this should be resolved as of last wednesday, feel free to reopen if you're still having issues
