### ISSUE TITLE
nsp command missing?

### ISSUE THREAD

**Issue by plynchnlm** [nodesecurity/nsp#82]
The readme implies that after you run "npm i nsp -g" you can run "nsp audit-shrinkwrap" but I did not find an "nsp" command.  I had to run "node node_modules/nsp/bin/nspCLI.js audit-package" (which did work, but....)

**Comment by pdehaan** [comment]
@plynchnlm Which OS are you using?
I just tried this on OSX using `$ npm i nsp@latest -g` and it worked as expected.

Also, which version of **nsp** are you using? (`node node_modules/nsp/bin/nspCLI.js version` in your case).

```
✗ nsp version
1.1.0

✗ npm info nsp version
1.1.0
```

I'm guessing from the fact that you're calling **nsp** from the ./node_modules/ directory, it didn't install globally.

**Comment by plynchnlm** [comment]
Never mind.  I thought I had set up my environment to include node_modules/.bin, but somehow that was left out.  "nsp" does get installed there and works fine.  Thanks for the help.
