### ISSUE TITLE
ansi-styles@2.2.0 doesn't exists on the registry

### ISSUE THREAD

**Issue by jfromaniello** [nodesecurity/nsp#83]
I am not sure if this version was removed or what but it doesn't show up in the registry.

**Comment by Verlic** [comment]
They just removed the 2.2.0 version and created v2.2.1: https://github.com/chalk/ansi-styles/releases/tag/v2.2.1

**Comment by Verlic** [comment]
Created PR #84 with the update in `npm-shrinkwrap.json`

**Comment by jpollard-cs** [comment]
:+1:

**Comment by akras14** [comment]
+1 2.2.0 in unpublished https://github.com/chalk/ansi-styles/issues/15

**Comment by nlf** [comment]
just published nsp@2.2.2 with this fixed, thanks for the reports

**Comment by jpollard-cs** [comment]
thanks for the quick turn-around!

**Comment by akras14** [comment]
Thanks!

**Comment by jfromaniello** [comment]
Thanks!
