### ISSUE TITLE
Do not post the entire package.json

### ISSUE THREAD

**Issue by majgis** [nodesecurity/nsp#94]
For packages stored in a private registry, it would preferable that their entire package.json was not posted.   Would it be possible to only post name, version, dependencies, devDependencies?

**Comment by majgis** [comment]
Would you take a PR for this feature?  Otherwise, I will create a separate package to sanitize the package.json.

**Comment by shamasis** [comment]
:+1:

**Comment by shamasis** [comment]
@majgis - as a solution for the issue #95, I made a workaround that allows one to exclude package and also suppress the additional package.json details.

https://gist.github.com/shamasis/e2969a1b9505d450586c90689061918d

**Comment by nlf** [comment]
i'd be open to a PR that strips the package.json down to the name, version, engine, dependencies, devDependencies, optionalDependencies, peerDependencies, and bundle(d)Dependencies properties.

those are currently the only fields we have near-future plans for, and we can always make additions later

**Comment by majgis** [comment]
Thank you.  I'll submit a PR this weekend if nobody wants to beat me to it.

**Comment by majgis** [comment]
@evilpacket suggested putting this behind a `--private` flag.  I will plan on doing that.

**Comment by pdehaan** [comment]
Shouldn't it be private by default though?
I don't see much point in posting a bunch of npm scripts and configs and other junk stored in the package.json if NSP doesn't care about it or use it.

**Comment by evilpacket** [comment]
Agreed. We were sitting on the fence about getting some of those things because we may analyze them in the future, but chances are the cli won't do that but our hook services will. 

Let's just make it the default. we may need to change that default in the future if we need some other piece of data.
